[build]
target = "x86_64-unknown-none.json"

[unstable]
# Added "alloc" here to fix the "crate not found" error
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
runner = "bootimage runner"
rustflags = [
    "-C", "target-feature=-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,+soft-float"
]