#[derive(Clone, Copy)]
pub struct LogoRect {
    pub x: i32,
    pub y: i32,
    pub w: i32,
    pub h: i32,
    pub highlight: bool,
}

pub const SNOWFLAKE_LOGO_RECTS: [LogoRect; 18] = [
    LogoRect {
        x: 8,
        y: 2,
        w: 2,
        h: 14,
        highlight: false,
    },
    LogoRect {
        x: 2,
        y: 8,
        w: 14,
        h: 2,
        highlight: false,
    },
    LogoRect {
        x: 8,
        y: 0,
        w: 2,
        h: 2,
        highlight: false,
    },
    LogoRect {
        x: 8,
        y: 16,
        w: 2,
        h: 2,
        highlight: false,
    },
    LogoRect {
        x: 0,
        y: 8,
        w: 2,
        h: 2,
        highlight: false,
    },
    LogoRect {
        x: 16,
        y: 8,
        w: 2,
        h: 2,
        highlight: false,
    },
    LogoRect {
        x: 2,
        y: 2,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 4,
        y: 4,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 6,
        y: 6,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 10,
        y: 10,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 12,
        y: 12,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 14,
        y: 14,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 14,
        y: 2,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 12,
        y: 4,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 10,
        y: 6,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 6,
        y: 10,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 4,
        y: 12,
        w: 2,
        h: 2,
        highlight: true,
    },
    LogoRect {
        x: 2,
        y: 14,
        w: 2,
        h: 2,
        highlight: true,
    },
];
